language: cpp
compiler: g++
notifications:
  email: false
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cmake
before_install:
- sudo apt-get install libopenmpi-dev
- sudo apt-get install g++-6
- sudo apt-get install libmpich-dev
install:
- export CXX="g++-6"
- chmod +x runProject.sh
script: "bash -c ./runProject.sh"
